INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 100. Computer Engineering Orientation.', 'F', '1', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '100');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 101. Fundamentals of Computer Science.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Appropriate Math Placement Level; or MATH 117 with a grade of C- or better; or MATH 118 with a grade of C- or better; or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '101');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 105. Fundamentals of Computer Science I Supplemental Instruction.', 'TBD', '1', 'CPE/CSC 101.', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '105');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 108. Accelerated Introduction to Computer Science.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 118 (or equivalent) with a grade of C- or better, significant experience in computer programming, and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '108');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 123. Introduction to Computing.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Basic computer literacy.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '123');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 133. Digital Design.', 'F,W,SP,SU', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', "An orientation course in student's major (EE 111 and EE 151; or CPE 100) and CPE/CSC 101.", 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '133');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 200. Special Problems for Undergraduates.', 'F,W,SP,SU', '1-2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '200');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 202. Data Structures.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 101 with a grade of C- or better; MATH 141 or MATH 221 with a grade of C- or better; or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '202');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 203. Project-Based Object-Oriented Programming and Design.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 202 with a grade of C- or better or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '203');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 233. Computer Design and Assembly Language Programming.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 133.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '233');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 290. Selected Topics.', 'TBD', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Open to undergraduate students and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '290');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 315. Computer Architecture.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103, or CSC/CPE 202 and CSC/CPE 203; and one of the CSC 225, CPE/EE 229, or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '315');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 316. Microcontrollers and Embedded Applications.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '316');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 321. Introduction to Computer Security.', 'F,W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '321');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 327. Digital Signals and Systems.', 'F,W', '3', 'CPE 367.', 'NA_RECOMMENDED_TEXT', 'EE 212, MATH 244.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '327');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 328. Discrete Time Signals and Systems.', 'F,W,SP', '3', 'CPE/EE 368.', 'NA_RECOMMENDED_TEXT', 'BMED 355 or EE 228.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '328');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 329. Microcontroller-Based Systems Design.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'EE 307 & EE 347, EE 229 & EE 269 or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '329');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 333. Computer Hardware Architecture and Design.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 101, CPE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '333');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 336. Microprocessor System Design.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '336');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 350. Capstone I.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '350');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 357. Systems Programming.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103 with a grade of C- or better or consent of instructor, or CSC/CPE 202 and CSC/CPE 203 with a grade of C- or better or consent of instructor; and CSC 225 or CPE/EE 229 or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '357');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 367. Digital Signals and Systems Laboratory.', 'F,W', '1', 'CPE 327.', 'NA_RECOMMENDED_TEXT', 'EE 242.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '367');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 368. Signals and Systems Laboratory.', 'F,W,SP', '1', 'CPE/EE 328.', 'NA_RECOMMENDED_TEXT', 'BMED 355 or EE 228.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '368');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 400. Special Problems for Undergraduates.', 'F,W,SP,SU', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '400');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 414. Robotic Systems Integration.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'EE/CPE 329 or EE/CPE 336 or CSC/CPE 357 or ME 305.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '414');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 416. Autonomous Mobile Robotics.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 329 or CPE/EE 336 or both CPE 315 and CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '416');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 419. Applied Parallel Computing.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'CPE 315.', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '419');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 422. Network and Web Security.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 464.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '422');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 426. Introduction to Hardware Security.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 315 or CPE 333; and CPE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '426');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 428. Computer Vision.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 327 or CPE/CSC 357 or EE 328 or ME 305.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '428');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 431. Compiler Construction.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 430.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '431');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 432. Digital Control Systems.', 'F', '3', 'CPE/EE 472.', 'EE 328 and EE 368.', 'EE 302 and EE 342; or CPE 327 and CPE 367.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '432');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 439. Introduction to Real-Time Operating Systems.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 329 or CPE/EE 336.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '439');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 441. Computer-Aided Design of VLSI Devices.', 'F', '4', 'NA_CONCURRENT_TEXT', 'EE 308 and EE 348, for students interested in analog design.', 'EE 307 and EE 347.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '441');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 442. Real Time Embedded Systems.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 329 or CPE/EE 336 or CPE 316.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '442');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 446. Design of Fault-Tolerant Digital Systems.', 'F', '4', 'NA_CONCURRENT_TEXT', 'STAT 350.', 'CPE/EE 329 or CPE/EE 336 or CPE 316.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '446');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 447. Stringed Musical Instrument Acoustics, Mechanics, and Transducer Design.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'EE/CPE 329 or EE/CPE 336 or CPE 316 or ME 305.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '447');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 450. Capstone II.', 'W', '3', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '450');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 453. Introduction to Operating Systems.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357, and CSC/CPE 225 or CPE/EE 229 or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '453');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 454. Implementation of Operating Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 453.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '454');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 458. Current Topics in Computer Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '458');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 461. Senior Project I.', 'F,W,SP,SU', '3', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '461');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 462. Senior Project II.', 'F,W,SP,SU', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 450.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '462');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 464. Introduction to Computer Networks.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'STAT 312 or STAT 321 or STAT 350.', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '464');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 465. Advanced Computer Networks.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 453 and CPE 464.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '465');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 469. Distributed Systems.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '469');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 470. Selected Advanced Topics.', 'TBD', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '470');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 471. Introduction to Computer Graphics.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '471');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 472. Digital Control Systems Laboratory.', 'F', '1', 'CPE/EE 432.', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '472');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 476. Real-Time 3D Computer Graphics Software.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 471.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '476');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 479. Selected Advanced Laboratory.', 'TBD', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '479');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 482. Advanced Topics in Systems for Computer Engineering.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '482');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 485. Autonomous Robot Navigation.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '485');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 488. Microelectronics and Electronics Packaging.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'MATE 210.', 'EE 112 or EE 113 or EE 201.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '488');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 493. Cooperative Education Experience.', 'F,W,SP,SU', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CPE', '493');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 494. Cooperative Education Experience.', 'F,W,SP,SU', '6', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CPE', '494');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 495. Cooperative Education Experience.', 'F,W,SP,SU', '12', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CPE', '495');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 515. Computer Architecture.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 315 or CPE 333, and graduate standing; or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CPE', '515');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 521. Computer Systems.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 329 or CPE/EE 336, or equivalent, and graduate standing or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CPE', '521');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 522. Advanced Real-Time Operating Systems Design.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 439.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '522');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 523. Digital Systems Design.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 329 or CPE/EE 336, and graduate standing.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CPE', '523');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 532. VLSI Circuit Testing.', 'F', '1', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'EE 531/CPE 541.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '532');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 541. Advanced VLSI Design.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 441/EE 431.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '541');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 542. Advanced Real Time Embedded Systems.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/EE 442.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CPE', '542');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 564. Computer Networks: Research Topics.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 464 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CPE', '564');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CPE 569. Distributed Computing.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348; and CPE/CSC 357; or graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CPE', '569');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 101. Fundamentals of Computer Science.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Appropriate Math Placement Level; or MATH 117 with a grade of C- or better; or MATH 118 with a grade of C- or better; or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '101');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 105. Fundamentals of Computer Science I Supplemental Instruction.', 'TBD', '1', 'CPE/CSC 101.', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '105');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 108. Accelerated Introduction to Computer Science.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 118 (or equivalent) with a grade of C- or better, significant experience in computer programming, and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '108');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 123. Introduction to Computing.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Basic computer literacy.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '123');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 171. Introduction to Interactive Entertainment.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '171');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 200. Special Problems for Undergraduates.', 'F,W,SP', '1-2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '200');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 202. Data Structures.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 101 with a grade of C- or better; MATH 141 or MATH 221 with a grade of C- or better; or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '202');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 203. Project-Based Object-Oriented Programming and Design.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 202 with a grade of C- or better or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '203');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 209. Problem Solving with Computers.', 'TBD', '1', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 101 or CSC/CPE 108 with a grade of C- or better, or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '209');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 225. Introduction to Computer Organization.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 202.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '225');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 231. Programming for Engineering Students.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 142; PHYS 121 or PHYS 131 or PHYS 141.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '231');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 232. Computer Programming for Scientists and Engineers.', 'F,W', '3', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 118 or equivalent.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '232');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 234. C and Unix.', 'W', '3', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 142.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '234');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 235. Fundamentals of Computer Science for Scientists and Engineers I.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'MATH 141 or MATH 161 with a grade of C- or better, or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '235');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 236. Fundamentals of Computer Science for Scientists and Engineers II.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 235 with a grade of C- or better, or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '236');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 290. Selected Topics.', 'TBD', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Open to undergraduate students and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '290');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 300. Professional Responsibilities.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357 and junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '300');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 301. Personal Software Process.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103, or CSC/CPE 202 and CSC/CPE 203.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '301');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 302. Computers and Society.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Junior standing; completion of GE Area A with grades of C- or better; completion of GE Area B1 with a grade of C- or better in at least one of the courses; and completion of GE Areas B2, B3, and B4.', 'NA_CROSS_LIST', 'Junior standing', 'JR', 'CSC', '302');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 303. Teaching Computer Science.', 'TBD', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103, with a grade of C- or better or consent of instructor, or CSC/CPE 202 and CSC/CPE 203, with a grade of C- or better or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '303');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 305. Individual Software Design and Development.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '305');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 307. Introduction to Software Engineering.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348; and CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '307');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 308. Software Engineering I.', 'F,W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '308');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 309. Software Engineering II.', 'W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 308 and CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '309');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 310. Computers for Poets.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Junior standing; completion of GE Area A with grades of C- or better; completion of GE Area B1 with a grade of C- or better in at least one of the courses; and completion of GE Areas B2, B3, and B4.', 'NA_CROSS_LIST', 'Junior standing', 'JR', 'CSC', '310');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 311. Computational Art.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Junior standing; completion of GE Area A with grades of C- or better; completion of GE Area B1 with a grade of C- or better in at least one of the courses; and completion of GE Areas B2, B3, and B4.', 'NA_CROSS_LIST', 'Junior standing', 'JR', 'CSC', '311');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 313. Teaching Computing.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 202.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '313');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 320. Practical Computer Security for Everyone.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Junior standing; completion of GE Area A with grades of C- or better; completion of GE Area B1 with a grade of C- or better in at least one of the courses; and completion of GE Areas B2, B3, and B4.', 'NA_CROSS_LIST', 'Junior standing', 'JR', 'CSC', '320');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 321. Introduction to Computer Security.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '321');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 323. Cryptography Engineering.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '323');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 325. Introduction to Privacy: Policy and Technology.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 300.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '325');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 344. Music Programming.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348; and CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '344');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 348. Discrete Structures.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103, with a grade of C- or better or consent of instructor, or CSC/CPE 202 and CSC/CPE 203, with a grade of C- or better or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '348');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 349. Design and  Analysis of Algorithms.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 and MATH 142; or CSC 348 and MATH 142; or CPE/CSC 102 and CPE/ CSC 103 and MATH 248; or CPE/CSC 202 and CPE/ CSC 203 and MATH 248.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '349');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 350. Computing for Interactive Arts Capstone I.', 'TBD', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'ART 384; CSC/CPE 103 or CSC/CPE 202; and junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '350');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 357. Systems Programming.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103 with a grade of C- or better or consent of instructor, or CSC/CPE 202 and CSC/CPE 203 with a grade of C- or better or consent of instructor; and CSC 225 or CPE/EE 229 or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '357');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 365. Introduction to Database Systems.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141; or CSC 348; or CPE/CSC 102 and CPE/CSC 103 and MATH 248; or CPE/CSC 202 and CPE/CSC 203 and MATH 248.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '365');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 366. Database Modeling, Design and Implementation.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 365.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '366');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 369. Introduction to Distributed Computing.', 'F,W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103, or CSC/CPE 202 and CSC/CPE 203; and one of the STAT 301, STAT 312, STAT 321 or STAT 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '369');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 371. Game Design.', 'W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 102 and CSC/CPE 103; or CSC/CPE 202 and junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '371');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 377. Introduction to Mixed Reality.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'ART 376.', 'CPE/CSC 202.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '377');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 378. Interactive Entertainment Engineering.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 102 and CPE/CSC 103, or CPE/CSC 202 and junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '378');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 400. Special Problems.', 'F,W,SP', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '400');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 402. Software Requirements Engineering.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 309.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '402');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 405. Software Construction.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 305 and CSC 402.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '405');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 406. Senior Project - Software Deployment.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 405.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '406');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 409. Current Topics in Software Engineering.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 309.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '409');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 410. Software Evaluation.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 349; STAT 301, STAT 312, STAT 321 or STAT 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '410');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 422. Network and Web Security.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 464.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '422');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 424. Software Security.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 307 or CPE/CSC 309; CPE/CSC 321.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '424');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 429. Current Topics in Computer Security.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 321 and CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '429');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 430. Programming Languages.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 349 and CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '430');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 431. Compiler Construction.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 430.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '431');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 435. Introduction to Object Oriented Design Using Graphical User Interfaces.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 305.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '435');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 436. Mobile Application Development.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '436');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 437. Dynamic Web Development.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357 with a grade of C- or better and CSC 365 with a grade of C- or better; or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '437');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 445. Theory of Computation I.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '445');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 448. Bioinformatics Algorithms.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 349.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '448');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 450. Computing for Interactive Arts Capstone II.', 'TBD', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'ART/CSC 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '450');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 453. Introduction to Operating Systems.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357, and CSC/CPE 225 or CPE/EE 229 or CPE/EE 233.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '453');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 454. Implementation of Operating Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 453.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '454');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 458. Current Topics in Computer Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '458');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 466. Knowledge Discovery from Data.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 349 and one of the STAT 302, STAT 312, STAT 321 or STAT 350.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '466');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 468. Database Management Systems Implementation.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 365.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '468');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 469. Distributed Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '469');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 471. Introduction to Computer Graphics.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 357.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '471');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 473. Advanced Rendering Techniques.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 471.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '473');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 474. Computer Animation.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 471.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '474');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 476. Real-Time 3D Computer Graphics Software.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 471.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '476');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 477. Scientific and Information Visualization.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 349.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '477');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 478. Current Topics in Computer Graphics.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 471.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '478');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 480. Artificial Intelligence.', 'F,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'either CSC/CPE 102 and CSC/CPE 103 with a grade of C- or better or consent of instructor; or CSC/CPE 202 with a grade of C- or better and junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '480');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 481. Knowledge Based Systems.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 480.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '481');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 482. Speech and Language Processing.', 'F,W', '4', 'NA_CONCURRENT_TEXT', 'CSC 349.', 'CSC 466 or CSC 480 or graduate standing.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '482');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 483. Current Topics in Human-Computer Interaction.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 484.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '483');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 484. User-Centered Interface Design and Development.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 308; junior standing.', 'NA_CROSS_LIST', 'junior standing', 'JR', 'CSC', '484');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 486. Human-Computer Interaction Theory and Design.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'NA_PREREQUISITE_TEXT', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '486');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 487. Deep Learning.', 'F', '4', 'NA_CONCURRENT_TEXT', 'CSC 466 or CSC 480.', 'CSC 349, and MATH 206 or MATH 244.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '487');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 489. Current Topics in Artificial Intelligence.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 480.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '489');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 490. Selected Advanced Topics.', 'SP', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '490');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 491. Senior Project I.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 309; and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '491');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 492. Senior Project II.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 491 and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '492');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 493. Cooperative Education Experience.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CSC', '493');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 494. Cooperative Education Experience.', 'F,W,SP', '6', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CSC', '494');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 495. Cooperative Education Experience.', 'F,W,SP', '12', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Sophomore standing and consent of instructor.', 'NA_CROSS_LIST', 'Sophomore standing', 'SO', 'CSC', '495');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 496. Selected Advanced Laboratory.', 'SP', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '496');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 497. Research Senior Project I.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 309; and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '497');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 498. Research Senior Project II.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 497 and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '498');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 500. Directed Study.', 'F,W,SP', '1-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Fully classified graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '500');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 508. Software Engineering I.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 307 or CSC 308 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '508');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 509. Software Engineering II.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 508 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '509');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 515. Computer Architecture.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE 315 or CPE 333, and graduate standing; or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '515');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 521. Computer Security.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CPE/CSC 321 and graduate standing.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '521');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 530. Languages and Translators.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 430 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '530');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 540. Theory of Computation II.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 445 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '540');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 550. Operating Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 453 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '550');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 560. Database Systems.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 365 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '560');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 564. Computer Networks: Research Topics.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC/CPE 464 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '564');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 566. Topics in Advanced Data Mining.', 'SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 466 or CSC 480 or CSC 582.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '566');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 569. Distributed Computing.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 141 or CSC 348; and CPE/CSC 357; or graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '569');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 570. Current Topics in Computer Science.', 'F,W', '2-4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Graduate standing and evidence of satisfactory preparation in computer science.', 'NA_CROSS_LIST', 'Graduate standing', 'GR', 'CSC', '570');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 572. Computer Graphics.', 'F', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Successful completion of CSC/CPE 471 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '572');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 580. Artificial Intelligence.', 'W', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 480 and graduate standing, or consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '580');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 581. Computer Support for Knowledge Management.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 480 or CSC 484 or consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '581');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 582. Computational Linguistics.', 'TBD', '4', 'NA_CONCURRENT_TEXT', 'CSC 580.', 'CSC 482 and graduate standing.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '582');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 590. Thesis Seminar.', 'F,W,SP', '1', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Graduate standing or consent of instructor.', 'NA_CROSS_LIST', 'Graduate standing', 'GR', 'CSC', '590');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 593. Cooperative Education Experience.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'Graduate standing', 'GR', 'CSC', '593');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 594. Cooperative Education Experience.', 'F,W,SP', '6', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'Graduate standing', 'GR', 'CSC', '594');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 595. Cooperative Education Experience.', 'F,W,SP', '12', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Graduate standing and consent of instructor.', 'NA_CROSS_LIST', 'Graduate standing', 'GR', 'CSC', '595');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 596. Research in Computer Science I.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'Consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '596');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 597. Research in Computer Science II.', 'F,W,SP', '2', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 596 and consent of instructor.', 'NA_CROSS_LIST', 'NA_STANDING_TEXT', 'NA', 'CSC', '597');

INSERT INTO `Courses` (`courseName`, `termsOffered`, `units`, `raw_concurrent_text`, `raw_recommended_text`, `raw_prerequisites_text`, `crossListedAs`, `raw_standing_text`, `standing`, `dept`, `courseNum`) VALUES ('CSC 599. Thesis.', 'F,W,SP', '4', 'NA_CONCURRENT_TEXT', 'NA_RECOMMENDED_TEXT', 'CSC 590; CSC 498 or CSC 597; selection of thesis committee; graduate standing; and consent of instructor.', 'NA_CROSS_LIST', 'graduate standing', 'GR', 'CSC', '599');